#!/usr/bin/env bash

set -euo pipefail

# Configuration
HOOKSDIR=$(dirname "$0")

# API key
chmod 600 "$HOOKSDIR/.boatns-auth"
. "$HOOKSDIR/.boatns-auth"

# Authenticate using BoatNS API
wget --output-document=- \
  --header="Authorization: Basic ${BOATNS_API_AUTH}" \
  --post-data="domain=${CERTBOT_DOMAIN}&validation=${CERTBOT_VALIDATION}" \
  https://boatns.com/api/v1/certbot/auth

# Wait 15 sec for public nameservers to be updated..
sleep 15

