#!/usr/bin/env bash

set -euo pipefail

# Configuration
HOOKSDIR=$(dirname "$0")
AUTHFILE="$HOOKSDIR/.boatns-auth"

# Check for domain specific authfile
if [[ -f "$AUTHFILE.$CERTBOT_DOMAIN" ]] ; then
  AUTHFILE="$AUTHFILE.$CERTBOT_DOMAIN"
fi

# Load API key
chmod 600 "$AUTHFILE"
. "$AUTHFILE"

# Authenticate using BoatNS API
wget --quiet \
  --output-document=- \
  --header="Authorization: Basic ${BOATNS_API_AUTH}" \
  --post-data="domain=${CERTBOT_DOMAIN}&validation=${CERTBOT_VALIDATION}" \
  https://boatns.com/api/v1/certbot/auth

# Wait 15 sec for public nameservers to be updated..
sleep 15

